"""ABINIT DFPT phonon inputs and anaddb eigenvector parsing.

The finite-displacement EFG workflow needs phonon frequencies and eigenvectors
to define the displacement directions.  This module generates the ABINIT
response-function (DFPT) input and the anaddb input that produce them, and
parses the anaddb eigenvector output into :class:`~quadrupolar_dft.
finite_displacement.PhononMode` objects.

Important: the generated DFPT input is a *starting template* built from your
equilibrium structure -- DFPT (especially with PAW) is sensitive to settings,
so converge and sanity-check it before trusting the modes.  The anaddb
eigenvector text layout also varies slightly between ABINIT versions; the parser
is anchored on stable markers, but verify it against your first real run (a
helper, :func:`modes_from_arrays`, lets you bypass the text parser entirely if
you already have frequencies and eigenvectors in hand).
"""

from __future__ import annotations

import re

import numpy as np

from .finite_displacement import PhononMode, _strip_comments, _tokens_after


def phonon_dfpt_input(base_structure_input: str) -> str:
    """Return a Gamma-point DFPT phonon ABINIT input from a static EFG input.

    Reuses the structure and electronic settings from ``base_structure_input``
    (the converged static EFG input), strips the EFG-only keywords, and prepends
    a two-dataset ground-state + response-function block.  The run writes a DDB
    file that anaddb post-processes.
    """

    natom = int(_tokens_after(_strip_comments(base_structure_input), "natom")[0])
    body = _strip_efg_keywords(base_structure_input)
    header = f"""# Gamma-point phonon (DFPT) generated by QuadrupolarDFT.
# VERIFY against your converged settings before production: DFPT (and PAW DFPT
# in particular) needs tight tolerances and an adequate k-mesh.
ndtset 2

# PAW + GGA DFPT needs the explicit XC kernel (Kxc), not the development scheme.
pawxcdev 0

# Dataset 1: ground state (tight wavefunction convergence for DFPT).
  kptopt1 1
  prtwf1 1
  tolwfr1 1.0d-22

# Dataset 2: response function, phonons at q = Gamma.
# iscf2 overrides the static input's iscf (which is often > 9 and is only valid
# for the ground state; the DFPT driver requires iscf <= 9).
  rfphon2 1
  rfatpol2 1 {natom}
  rfdir2 1 1 1
  nqpt2 1
  qpt2 0.0 0.0 0.0
  getwfk2 1
  kptopt2 2
  iscf2 7
  tolvrs2 1.0d-10

# ---- structure and electronic settings (from the static EFG input) ----
"""
    return header + body.strip() + "\n"


def anaddb_input(ddb_filename: str = "phonono_DDB") -> str:
    """Return an anaddb input that prints Gamma eigenvectors from a DDB file."""

    return f"""# anaddb: Gamma-point phonon frequencies and eigenvectors.
# Run as:  anaddb anaddb.abi  (with a files file pointing at the DDB), or with
# the modern  anaddb --input anaddb.abi  interface.
ifcflag 0
eivec 1

# One phonon q-point: Gamma.
nph1l 1
qph1l 0.0 0.0 0.0 1.0

# DDB produced by the DFPT run.
# ddb file: {ddb_filename}
"""


#: Modes below this wavenumber are treated as acoustic/imaginary and skipped.
ACOUSTIC_CUTOFF_CM_INV = 1.0


def modes_from_arrays(
    wavenumbers_cm_inv,
    eigendisplacements,
    masses_amu,
    *,
    mass_weighted: bool = False,
    min_wavenumber_cm_inv: float = ACOUSTIC_CUTOFF_CM_INV,
) -> list[PhononMode]:
    """Build PhononMode objects from frequency and eigenvector arrays.

    ``eigendisplacements`` has shape ``(n_modes, natom, 3)``.  By default they
    are treated as Cartesian eigendisplacements (the physical atomic motion) and
    converted to mass-weighted eigenvectors; pass ``mass_weighted=True`` if they
    are already dynamical-matrix eigenvectors.  Modes below
    ``min_wavenumber_cm_inv`` (acoustic or imaginary at Gamma) are skipped.
    """

    frequencies = np.asarray(wavenumbers_cm_inv, dtype=float)
    vectors = np.asarray(eigendisplacements, dtype=float)
    masses = np.asarray(masses_amu, dtype=float)
    if vectors.ndim != 3 or vectors.shape[2] != 3:
        raise ValueError("eigendisplacements must have shape (n_modes, natom, 3)")
    modes: list[PhononMode] = []
    for index, frequency in enumerate(frequencies):
        if frequency < min_wavenumber_cm_inv:
            continue  # skip acoustic/imaginary modes
        vector = vectors[index]
        eigenvector = vector if mass_weighted else vector * np.sqrt(masses)[:, None]
        modes.append(
            PhononMode(
                wavenumber_cm_inv=float(frequency),
                eigenvector=eigenvector,
                label=f"mode{index:03d}",
            )
        )
    return modes


_FREQ_HEADER = re.compile(r"Phonon frequencies in cm-1", re.IGNORECASE)
_MODE_HEADER = re.compile(r"Mode number\s+(\d+)", re.IGNORECASE)
_NUM = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eEdD][-+]?\d+)?"


def parse_anaddb_modes(
    text: str,
    masses_amu,
    *,
    natom: int | None = None,
) -> list[PhononMode]:
    """Parse anaddb phonon frequencies and eigendisplacements into modes.

    Expects the anaddb ``eivec`` output: a ``Phonon frequencies in cm-1`` block
    followed by per-mode ``Mode number`` blocks, each listing ``natom`` rows of
    Cartesian (real, imaginary) components.  Imaginary parts are dropped
    (Gamma-point modes are real).  Negative/acoustic frequencies are skipped.

    Returns modes in the same order as the frequency list.  Verify against your
    first anaddb run; use :func:`modes_from_arrays` if the layout differs.
    """

    masses = np.asarray(masses_amu, dtype=float)
    if natom is None:
        natom = masses.shape[0]

    frequencies = _parse_anaddb_frequencies(text)
    displacements = _parse_anaddb_eigendisplacements(text, natom)
    if not displacements:
        raise ValueError(
            "no eigendisplacement blocks found; run anaddb with eivec and check "
            "the output layout, or use modes_from_arrays()"
        )
    # anaddb omits eigendisplacements for some modes (e.g. the ~0 cm^-1 acoustic
    # modes), so pair by mode number (1-based, matching the frequency order)
    # rather than by list position -- otherwise the modes after a gap would be
    # assigned the wrong frequency.
    aligned_freqs: list[float] = []
    aligned_disp: list[np.ndarray] = []
    for mode_number, vector in sorted(displacements.items()):
        index = mode_number - 1
        if 0 <= index < len(frequencies):
            aligned_freqs.append(frequencies[index])
            aligned_disp.append(vector)
    return modes_from_arrays(
        aligned_freqs, np.array(aligned_disp), masses, mass_weighted=False
    )


def _parse_anaddb_frequencies(text: str) -> list[float]:
    match = _FREQ_HEADER.search(text)
    if match is None:
        return []
    tail = text[match.end():]
    values: list[float] = []
    for line in tail.splitlines():
        stripped = line.lstrip("-").strip()
        tokens = stripped.split()
        if not tokens:
            if values:
                break
            continue
        try:
            row = [float(token.replace("d", "e").replace("D", "e")) for token in tokens]
        except ValueError:
            if values:
                break
            continue
        values.extend(row)
    return values


def _parse_anaddb_eigendisplacements(text: str, natom: int) -> dict[int, np.ndarray]:
    """Read the Cartesian real eigendisplacement of each mode, keyed by mode number.

    anaddb prints, per mode, a ``Mode number N  Energy ...`` header then, for
    each atom, two ``;``-prefixed lines: ``;  <atom_index>  re_x re_y re_z`` and
    ``;  im_x im_y im_z``. We keep the real triplet (dropping the atom index and
    the imaginary part). Non-``;`` lines (e.g. "Attention : low frequency mode")
    are ignored. Modes with no eigendisplacement block (e.g. acoustic modes) are
    simply absent from the returned mapping.
    """

    blocks: dict[int, np.ndarray] = {}
    matches = list(_MODE_HEADER.finditer(text))
    for index, match in enumerate(matches):
        mode_number = int(match.group(1))
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        triplets: list[list[float]] = []
        for line in text[start:end].splitlines():
            if not line.lstrip().startswith(";"):
                continue
            numbers = [
                float(token.replace("d", "e").replace("D", "e"))
                for token in re.findall(_NUM, line)
            ]
            if len(numbers) == 4:  # atom_index, re_x, re_y, re_z
                triplets.append(numbers[1:4])
            # len(numbers) == 3 is the imaginary part for that atom -> skip.
            if len(triplets) == natom:
                break
        if len(triplets) == natom:
            blocks[mode_number] = np.array(triplets, dtype=float)
    return blocks


def _strip_efg_keywords(text: str) -> str:
    """Remove EFG-only keywords (nucefg/quadmom/prtefg) from a static input."""

    out_lines = []
    skip_continuation = False
    for line in text.splitlines():
        stripped = line.strip().lower()
        keyword = stripped.split()[0] if stripped and stripped[0].isalpha() else ""
        if keyword in {"nucefg", "quadmom", "prtefg"}:
            skip_continuation = keyword == "quadmom" and not _has_three_numbers(line)
            continue
        if skip_continuation:
            # A wrapped quadmom value line (rare); stop skipping at next keyword.
            if stripped and stripped[0].isalpha():
                skip_continuation = False
            else:
                continue
        out_lines.append(line)
    return "\n".join(out_lines)


def _has_three_numbers(line: str) -> bool:
    return len(re.findall(_NUM, line.split("#", 1)[0])) >= 3
