"""Structural relaxation stage for the finite-temperature EFG workflow.

A static DFT EFG is only meaningful at an energy minimum: starting geometry that
is not relaxed leaves residual forces that show up as imaginary phonon modes at
Gamma and bias the equilibrium asymmetry ``eta``.  This module adds a relaxation
stage *in front of* the phonon -> displace -> collect chain, and -- crucially --
emits the same artifact that chain already consumes: a converged static EFG
``.abi`` with the relaxed atomic positions substituted in.  Nothing downstream
changes; you just point ``phonon``/``displace`` at the relaxed input.

Scope: internal coordinates only (``ionmov``, ``optcell 0``).  The cell is held
at the input (experimental) value, which is the standard choice for molecular
crystals -- PBE tends to over-expand the lattice, and a cell relaxation can
worsen the EFG relative to the measured geometry.  Full cell relaxation (the
quasi-harmonic thermal-expansion path) is a later add and would need a separate
``acell``/``rprim`` substitution.

The relaxed geometry is read from the ABINIT output footer
(``-outvars: echo values of variables after computation``), which echoes every
input variable at its *final* value -- the same place abipy reads the relaxed
structure.  That footer uses the ordinary ABINIT input ``varname value(s)``
syntax, so :func:`~quadrupolar_dft.finite_displacement.parse_abinit_structure`
parses it directly.
"""

from __future__ import annotations

import numpy as np

from .abinit_phonon import _strip_efg_keywords
from .finite_displacement import (
    Crystal,
    abinit_input_with_positions,
    parse_abinit_structure,
)

#: Footer marker that precedes ABINIT's echo of the final (relaxed) variables.
#: ABINIT prints "-outvars: echo values of variables after computation --------";
#: we match on the stable substring so spacing/dash-count changes between
#: versions do not break the parser. (The header echo says "preprocessed input
#: variables" instead, so this only matches the post-computation block.)
_FOOTER_MARKER = "outvars: echo values of variables after computation"


def relax_input(
    base_static_input: str,
    *,
    ionmov: int = 2,
    ntime: int = 50,
    tolmxf: float = 5.0e-6,
) -> str:
    """Return an ionic-relaxation ABINIT input from a static EFG input.

    Reuses the structure and electronic settings from ``base_static_input`` (the
    converged static EFG input), strips the EFG-only keywords (no EFG is needed
    while relaxing), and prepends a geometry-optimization block.  The cell is
    held fixed (``optcell 0``); only the atomic positions move.

    ``ionmov 2`` is BFGS on the forces; ``tolmxf`` is the force-convergence
    threshold (Ha/Bohr) and ``ntime`` the maximum number of ionic steps.  The
    base input's ``tolvrs``/``nstep`` still govern the SCF convergence within
    each ionic step.
    """

    body = _strip_efg_keywords(base_static_input)
    header = f"""# Structural relaxation (ionic positions, fixed cell) generated by
# QuadrupolarDFT. VERIFY the tolerances/k-mesh against your converged static
# settings before trusting the relaxed geometry.
#
# Internal coordinates only: the cell is held at the input value (optcell 0).
# For molecular crystals this is usually what you want -- relax the geometry at
# the experimental cell rather than letting GGA over-expand the lattice.

# Geometry optimization: BFGS on the forces.
ionmov {ionmov}
optcell 0
ntime {ntime}
tolmxf {tolmxf:.1e}

# ---- structure and electronic settings (from the static EFG input) ----
"""
    return header + body.strip() + "\n"


def parse_relaxed_structure(abo_text: str, base_input: str) -> Crystal:
    """Return the relaxed structure from an ABINIT relaxation output.

    Reads the relaxed atomic positions from the output footer
    (``-outvars: echo values of variables after computation``) and combines them
    with the cell and species ordering of ``base_input``.  Because the cell is
    held fixed during the relaxation (``optcell 0``), only the positions are
    taken from the output; the lattice comes from the (trusted) base input,
    which also guards against any unit/precision drift in the echoed cell.

    Raises ``ValueError`` if the footer is absent -- that means the ABINIT run
    did not complete, so the geometry is not converged and must not be used.
    """

    marker = abo_text.rfind(_FOOTER_MARKER)
    if marker == -1:
        raise ValueError(
            "no '-outvars ... after computation' footer in the ABINIT output; the "
            "relaxation did not complete. Check the .abo for errors before using it."
        )
    footer = abo_text[marker:]
    relaxed = parse_abinit_structure(footer)
    base_crystal = parse_abinit_structure(base_input)
    if relaxed.natom != base_crystal.natom:
        raise ValueError(
            f"relaxed geometry has {relaxed.natom} atoms but the base input has "
            f"{base_crystal.natom}; are they the same structure?"
        )
    # Re-express the relaxed positions in the base (experimental) cell: recover
    # the relaxed reduced coordinates, then map them through the base lattice.
    relaxed_xred = relaxed.cart_angstrom @ np.linalg.inv(relaxed.lattice_angstrom)
    cart = relaxed_xred @ base_crystal.lattice_angstrom
    return Crystal(base_crystal.lattice_angstrom, base_crystal.species_z, cart)


def relaxed_input(base_static_input: str, abo_text: str) -> str:
    """Return ``base_static_input`` with its positions replaced by the relaxed ones.

    The result is a static EFG ``.abi`` (EFG keywords intact) at the relaxed
    geometry -- the input the ``phonon``/``displace`` stages expect.
    """

    crystal = parse_relaxed_structure(abo_text, base_static_input)
    return abinit_input_with_positions(base_static_input, crystal)
